PlanB.Butler.Admin/PlanB.Butler.Admin/Controllers/MealController.cs
// Copyright (c) PlanB. GmbH. All Rights Reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using PlanB.Butler.Admin.Contracts;
using PlanB.Butler.Admin.Models;

namespace PlanB.Butler.Admin.Controllers
{
    /// <summary>
    /// MealController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class MealController : Controller
    {
        /// <summary>
        /// The meal service.
        /// </summary>
        private readonly IMealService mealService;

        /// <summary>
        /// Initializes a new instance of the <see cref="MealController"/> class.
        /// </summary>
        /// <param name="mealSvc">The meal SVC.</param>
        public MealController(IMealService mealSvc) => this.mealService = mealSvc;

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>Meals.</returns>
        public IActionResult Index()
        {
            var meals = this.mealService.GetMeals().Result;
            return this.View(meals);
        }

        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Create()
        {
            return this.View();
        }

        /// <summary>
        /// Creates the specified meal.
        /// </summary>
        /// <param name="meal">The meal.</param>
        /// <returns>Meal.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CorrelationId,Date,Price,Name,Restaurant")] MealViewModel meal)
        {
            if (this.ModelState.IsValid)
            {
                var result = await this.mealService.CreateMeal(meal);
                return this.RedirectToAction("Index");
            }

            return this.View(meal);
        }

        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="meal">The meal.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,CorrelationId,Date,Price,Name,Restaurant")] MealViewModel meal)
        {
            if (id != meal.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                var result = await this.mealService.UpdateMeal(meal);
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(meal);
        }

        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Meal.</returns>
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return this.NotFound();
            }

            var meal = await this.mealService.GetMeal(id);

            if (meal == null)
            {
                return this.NotFound();
            }

            return this.View(meal);
        }

        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return this.NotFound();
            }

            var meal = await this.mealService.GetMeal(id);

            if (meal == null)
            {
                return this.NotFound();
            }

            return this.View(meal);
        }

        /// <summary>
        /// Deletes the confirmed.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await this.mealService.DeleteMeal(id);

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

PlanB.Butler.Admin/PlanB.Butler.Admin/Controllers/RestaurantController.cs
// Copyright (c) PlanB. GmbH. All Rights Reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PlanB.Butler.Admin.Contracts;
using PlanB.Butler.Admin.Models;

namespace PlanB.Butler.Admin.Controllers
{
    /// <summary>
    /// RestaurantController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class RestaurantController : Controller
    {
        /// <summary>
        /// restaurantService
        /// </summary>
        /// GET: /<controller>
        private readonly IRestaurantService restaurantService;

        /// <summary>
        /// Initializes a new instance of the <see cref="RestaurantController"/> class.
        /// </summary>
        /// <param name="restserv">The restaurant SVC.</param>
        public RestaurantController(IRestaurantService restserv) => this.restaurantService = restserv;

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>Index.</returns>
        public IActionResult Index()
        {
            var restaurant = this.restaurantService.GetRestaurants().Result;
            return this.View(restaurant);
        }

        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Create()
        {
            return this.View();
        }

        /// <summary>
        /// Creates the specified meal.
        /// </summary>
        /// <param name="restaurant">The meal.</param>
        /// <returns>Meal.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, CorrelationId, Date,Price,Name,Restaurant,PhoneNumber,City, Street, PostalCode, Url, EmailAddress")] RestaurantViewModel restaurant)
        {
            if (this.ModelState.IsValid)
            {
                var result = await this.restaurantService.CreateRestaurant(restaurant);
                return this.RedirectToAction("Index");
            }

            return this.View(restaurant);
        }

        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="restaurant">The meal.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,CorrelationId, Date,Price,Name,Restaurant,PhoneNumber,City, Street, PostalCode, Url, EmailAddress")] RestaurantViewModel restaurant)
        {
            if (id != restaurant.Id)
            {
                return this.NotFound();
            }

            var json = JsonConvert.SerializeObject(restaurant);
            Console.WriteLine(json);
            if (this.ModelState.IsValid)
            {
                var result = await this.restaurantService.UpdateRestaurant(restaurant);
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(restaurant);
        }

        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Meal.</returns>
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return this.NotFound();
            }

            var restaurant = await this.restaurantService.GetRestaurant(id);

            if (restaurant == null)
            {
                return this.NotFound();
            }

            return this.View(restaurant);
        }
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return this.NotFound();
            }

            var restaurant = await this.restaurantService.GetRestaurant(id);

            if (restaurant == null)
            {
                return this.NotFound();
            }

            return this.View(restaurant);
        }

        /// <summary>
        /// Deletes the confirmed.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await this.restaurantService.DeleteRestaurant(id);

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

PlanB.Butler.Admin/PlanB.Butler.Admin/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlanB.Butler.Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PlanB.Butler.Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meal" asp-action="Index">Meal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurant</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PlanB.Butler.Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>